---
- hosts: localhost
  vars:
    organization: govtech
    project: tt
  tasks:
    - name: gcp
      tags: "{{ organization }}/{{ project }}"
      vars:
        dir_name: .gcp
      block:
        - name: "create ~/{{ dir_name }}"
          file:
            path: "~/{{ dir_name }}"
            state: directory
        - name: copying files
          copy:
            src: "{{ item }}"
            dest: "~/{{ dir_name }}"
          loop: "{{ lookup('fileglob', './dotfiles/{{ organization }}/{{ project }}/{{ dir_name }}/*', wantlist=True) }}"

    - name: aws
      tags: "{{ organization }}/{{ project }}"
      vars:
        dir_name: .aws
      block:
        - name: "create ~/{{ dir_name }}"
          file:
            path: "~/{{ dir_name }}"
            state: directory
        - name: copying files
          copy:
            src: "{{ item }}"
            dest: "~/{{ dir_name }}"
          loop: "{{ lookup('fileglob', './dotfiles/{{ organization }}/{{ project }}/{{ dir_name }}/*', wantlist=True) }}"

    - name: tt aws otp
      tags: "{{ organization }}/{{ project }}"
      vars:
        dir_name: .tt_aws_otp
      block:
        - name: "create ~/{{ dir_name }}"
          file:
            path: "~/{{ dir_name }}"
            state: directory
        - name: copying files
          copy:
            src: "{{ item }}"
            dest: "~/{{ dir_name }}"
          loop: "{{ lookup('fileglob', './dotfiles/{{ organization }}/{{ project }}/{{ dir_name }}/*', wantlist=True) }}"

    - name: ssh
      tags: "{{ organization }}/{{ project }}"
      vars:
        dir_name: .ssh
      block:
        - name: "create ~/{{ dir_name }}"
          file:
            path: "~/{{ dir_name }}"
            state: directory
        - name: copying files
          copy:
            src: "{{ item }}"
            dest: "~/{{ dir_name }}"
          loop: "{{ lookup('fileglob', './dotfiles/{{ organization }}/{{ project }}/{{ dir_name }}/*', wantlist=True) }}"
